name: fork yaml
on: 
  fork
jobs:
  fork_test:
    runs_on: ubuntu-latest
    steps:
      - name: testing fork checkout
        uses: actions/checkout@v4.2.2
      
      - name: print
        run: echo hello world
        
